extractors:
  - py-feat

extracted_path: data/extracted
correlations_path: data/correlations.csv
  
extractors_features:
  py-feat:
    used:
      - leftShoulder
      - rightShoulder
      - leftElbow
      - rightElbow
      - leftWrist
      - rightWrist
      - leftEye
    all:
      - nose
      - leftEyeInner
      - leftEye
      - leftEyeOuter
      - rightEyeInner
      - rightEye
      - rightEyeOuter
      - leftEar
      - rightEar
      - mouthLeft
      - mouthRight
      - leftShoulder
      - rightShoulder
      - leftElbow
      - rightElbow
      - leftWrist
      - rightWrist
      - leftPinky
      - rightPinky
      - leftIndex
      - rightIndex
      - leftThumb
      - rightThumb
      - leftHip
      - rightHip
      - leftKnee
      - rightKnee
      - leftAnkle
      - rightAnkle
      - leftHeel
      - rightHeel
      - leftFootIndex
      - rightFootIndex
