# Configurations of clip yielding
clip:
  length: 10
  overlap: 5

# Extractors used in this particular cofiguration
extractors:
  - pyafar
  - mediapipe

# Path to the folder where all extracted data is stored
extracted_path: data/extracted/

# Path to the file where a file with all computer correlations will be stored
correlations_path: data/correlations.csv
  
extractors_features:
  # Mediapipe features
  mediapipe:
    used:
      - leftShoulder
      - rightShoulder
      - leftElbow
      - rightElbow
      - leftWrist
      - rightWrist
      - leftEye
    all:
      - nose
      - leftEyeInner
      - leftEye
      - leftEyeOuter
      - rightEyeInner
      - rightEye
      - rightEyeOuter
      - leftEar
      - rightEar
      - mouthLeft
      - mouthRight
      - leftShoulder
      - rightShoulder
      - leftElbow
      - rightElbow
      - leftWrist
      - rightWrist
      - leftPinky
      - rightPinky
      - leftIndex
      - rightIndex
      - leftThumb
      - rightThumb
      - leftHip
      - rightHip
      - leftKnee
      - rightKnee
      - leftAnkle
      - rightAnkle
      - leftHeel
      - rightHeel
      - leftFootIndex
      - rightFootIndex
  # Pyfeat features
  pyafar:
    used:
      - Pitch
      - Roll
      - Yaw
      - Eye Aspect Ratio
      - Mouth Aspect Ratio
      - Occ_au_01
      - Occ_au_02
      - Occ_au_04
      - Occ_au_07
      - Occ_au_15
      - Occ_au_23
      - Occ_au_24
      - Int_au_06
      - Int_au_10
      - Int_au_12
      - Int_au_14
      - Int_au_17
    all:
      # Too much, but can also yield normalized facial landmarks