# Data paths
dataset_path: ../VoxCeleb_v2_chosen/test_comp_1
extracted_features_raw_path: data/extracted
correlations_path: data/correlations.csv

# High-level video processing options
compress_videos: True
extract_features: False
compute_correlations: False

# Video compression
compression_level: 1 

# Feature extraction
extractors:
  - py-feat

extractors_features:
  py-feat:
    used:
      - leftShoulder
      - rightShoulder
      - leftElbow
      - rightElbow
      - leftWrist
      - rightWrist
      - leftEye
    all:
      - nose
      - leftEyeInner
      - leftEye
      - leftEyeOuter
      - rightEyeInner
      - rightEye
      - rightEyeOuter
      - leftEar
      - rightEar
      - mouthLeft
      - mouthRight
      - leftShoulder
      - rightShoulder
      - leftElbow
      - rightElbow
      - leftWrist
      - rightWrist
      - leftPinky
      - rightPinky
      - leftIndex
      - rightIndex
      - leftThumb
      - rightThumb
      - leftHip
      - rightHip
      - leftKnee
      - rightKnee
      - leftAnkle
      - rightAnkle
      - leftHeel
      - rightHeel
      - leftFootIndex
      - rightFootIndex

extracted_features_raw_path:
  - data/extracted

# Computation of correlations


