# Features of clips
clip:
  length: 10
  overlap: 5

# Path to the folder where all extracted data is stored
extracted_path: data/extracted/

# Extractors used in this particular cofiguration
extractors:
  - pyfeat
  - mediapipe

# Pyfeat configuration
pyfeat:
  ...

# Mediapipe configuration
mediapipe:
  ...
