# Features of clips
clip:
  length: 10
  overlap: 5

# Path to the folder where all extracted data is stored
extracted_path: data/extracted/

# Path to the file where a file with all computer correlations will be stored
correlations_path: data/correlations.csv

# Extractors used in this particular cofiguration
extractors:
  - pyfeat
  - mediapipe
  
extractors_features:
  # Mediapipe features
  mediapipe:
    used:
      - leftShoulder
      - rightShoulder
      - leftElbow
      - rightElbow
      - leftWrist
      - rightWrist
    all:
      - nose
      - leftEyeInner
      - leftEye
      - leftEyeOuter
      - rightEyeInner
      - rightEye
      - rightEyeOuter
      - leftEar
      - rightEar
      - mouthLeft
      - mouthRight
      - leftShoulder
      - rightShoulder
      - leftElbow
      - rightElbow
      - leftWrist
      - rightWrist
      - leftPinky
      - rightPinky
      - leftIndex
      - rightIndex
      - leftThumb
      - rightThumb
      - leftHip
      - rightHip
      - leftKnee
      - rightKnee
      - leftAnkle
      - rightAnkle
      - leftHeel
      - rightHeel
      - leftFootIndex
      - rightFootIndex
  # Pyfeat features
  pyfeat:
    used:
      - Pitch
      - Roll
      - Yaw
      - AU01
      - AU02
      - AU04
      - AU05
      - AU06
      - AU07
      - AU09
      - AU10
      - AU11
      - AU12
      - AU14
      - AU15
      - AU17
      - AU20
      - AU23
      - AU24
      - AU25
      - AU26
      - AU28
      - AU43
    all:
      - FaceRectX
      - FaceRectY
      - FaceRectWidth
      - FaceRectHeight
      - FaceScore
      - x_0
      - x_1
      - x_2
      - x_3
      - x_4
      - x_5
      - x_6
      - x_7
      - x_8
      - x_9
      - x_10
      - x_11
      - x_12
      - x_13
      - x_14
      - x_15
      - x_16
      - x_17
      - x_18
      - x_19
      - x_20
      - x_21
      - x_22
      - x_23
      - x_24
      - x_25
      - x_26
      - x_27
      - x_28
      - x_29
      - x_30
      - x_31
      - x_32
      - x_33
      - x_34
      - x_35
      - x_36
      - x_37
      - x_38
      - x_39
      - x_40
      - x_41
      - x_42
      - x_43
      - x_44
      - x_45
      - x_46
      - x_47
      - x_48
      - x_49
      - x_50
      - x_51
      - x_52
      - x_53
      - x_54
      - x_55
      - x_56
      - x_57
      - x_58
      - x_59
      - x_60
      - x_61
      - x_62
      - x_63
      - x_64
      - x_65
      - x_66
      - x_67
      - y_0
      - y_1
      - y_2
      - y_3
      - y_4
      - y_5
      - y_6
      - y_7
      - y_8
      - y_9
      - y_10
      - y_11
      - y_12
      - y_13
      - y_14
      - y_15
      - y_16
      - y_17
      - y_18
      - y_19
      - y_20
      - y_21
      - y_22
      - y_23
      - y_24
      - y_25
      - y_26
      - y_27
      - y_28
      - y_29
      - y_30
      - y_31
      - y_32
      - y_33
      - y_34
      - y_35
      - y_36
      - y_37
      - y_38
      - y_39
      - y_40
      - y_41
      - y_42
      - y_43
      - y_44
      - y_45
      - y_46
      - y_47
      - y_48
      - y_49
      - y_50
      - y_51
      - y_52
      - y_53
      - y_54
      - y_55
      - y_56
      - y_57
      - y_58
      - y_59
      - y_60
      - y_61
      - y_62
      - y_63
      - y_64
      - y_65
      - y_66
      - y_67
      - Pitch
      - Roll
      - Yaw
      - X
      - Y
      - Z
      - AU01
      - AU02
      - AU04
      - AU05
      - AU06
      - AU07
      - AU09
      - AU10
      - AU11
      - AU12
      - AU14
      - AU15
      - AU17
      - AU20
      - AU23
      - AU24
      - AU25
      - AU26
      - AU28
      - AU43
      - anger
      - disgust
      - fear
      - happiness
      - sadness
      - surprise
      - neutral
      - Identity_1
      - Identity_2
      - Identity_3
      - Identity_4
      - Identity_5
      - Identity_6
      - Identity_7
      - Identity_8
      - Identity_9
      - Identity_10
      - Identity_11
      - Identity_12
      - Identity_13
      - Identity_14
      - Identity_15
      - Identity_16
      - Identity_17
      - Identity_18
      - Identity_19
      - Identity_20
      - Identity_21
      - Identity_22
      - Identity_23
      - Identity_24
      - Identity_25
      - Identity_26
      - Identity_27
      - Identity_28
      - Identity_29
      - Identity_30
      - Identity_31
      - Identity_32
      - Identity_33
      - Identity_34
      - Identity_35
      - Identity_36
      - Identity_37
      - Identity_38
      - Identity_39
      - Identity_40
      - Identity_41
      - Identity_42
      - Identity_43
      - Identity_44
      - Identity_45
      - Identity_46
      - Identity_47
      - Identity_48
      - Identity_49
      - Identity_50
      - Identity_51
      - Identity_52
      - Identity_53
      - Identity_54
      - Identity_55
      - Identity_56
      - Identity_57
      - Identity_58
      - Identity_59
      - Identity_60
      - Identity_61
      - Identity_62
      - Identity_63
      - Identity_64
      - Identity_65
      - Identity_66
      - Identity_67
      - Identity_68
      - Identity_69
      - Identity_70
      - Identity_71
      - Identity_72
      - Identity_73
      - Identity_74
      - Identity_75
      - Identity_76
      - Identity_77
      - Identity_78
      - Identity_79
      - Identity_80
      - Identity_81
      - Identity_82
      - Identity_83
      - Identity_84
      - Identity_85
      - Identity_86
      - Identity_87
      - Identity_88
      - Identity_89
      - Identity_90
      - Identity_91
      - Identity_92
      - Identity_93
      - Identity_94
      - Identity_95
      - Identity_96
      - Identity_97
      - Identity_98
      - Identity_99
      - Identity_100
      - Identity_101
      - Identity_102
      - Identity_103
      - Identity_104
      - Identity_105
      - Identity_106
      - Identity_107
      - Identity_108
      - Identity_109
      - Identity_110
      - Identity_111
      - Identity_112
      - Identity_113
      - Identity_114
      - Identity_115
      - Identity_116
      - Identity_117
      - Identity_118
      - Identity_119
      - Identity_120
      - Identity_121
      - Identity_122
      - Identity_123
      - Identity_124
      - Identity_125
      - Identity_126
      - Identity_127
      - Identity_128
      - Identity_129
      - Identity_130
      - Identity_131
      - Identity_132
      - Identity_133
      - Identity_134
      - Identity_135
      - Identity_136
      - Identity_137
      - Identity_138
      - Identity_139
      - Identity_140
      - Identity_141
      - Identity_142
      - Identity_143
      - Identity_144
      - Identity_145
      - Identity_146
      - Identity_147
      - Identity_148
      - Identity_149
      - Identity_150
      - Identity_151
      - Identity_152
      - Identity_153
      - Identity_154
      - Identity_155
      - Identity_156
      - Identity_157
      - Identity_158
      - Identity_159
      - Identity_160
      - Identity_161
      - Identity_162
      - Identity_163
      - Identity_164
      - Identity_165
      - Identity_166
      - Identity_167
      - Identity_168
      - Identity_169
      - Identity_170
      - Identity_171
      - Identity_172
      - Identity_173
      - Identity_174
      - Identity_175
      - Identity_176
      - Identity_177
      - Identity_178
      - Identity_179
      - Identity_180
      - Identity_181
      - Identity_182
      - Identity_183
      - Identity_184
      - Identity_185
      - Identity_186
      - Identity_187
      - Identity_188
      - Identity_189
      - Identity_190
      - Identity_191
      - Identity_192
      - Identity_193
      - Identity_194
      - Identity_195
      - Identity_196
      - Identity_197
      - Identity_198
      - Identity_199
      - Identity_200
      - Identity_201
      - Identity_202
      - Identity_203
      - Identity_204
      - Identity_205
      - Identity_206
      - Identity_207
      - Identity_208
      - Identity_209
      - Identity_210
      - Identity_211
      - Identity_212
      - Identity_213
      - Identity_214
      - Identity_215
      - Identity_216
      - Identity_217
      - Identity_218
      - Identity_219
      - Identity_220
      - Identity_221
      - Identity_222
      - Identity_223
      - Identity_224
      - Identity_225
      - Identity_226
      - Identity_227
      - Identity_228
      - Identity_229
      - Identity_230
      - Identity_231
      - Identity_232
      - Identity_233
      - Identity_234
      - Identity_235
      - Identity_236
      - Identity_237
      - Identity_238
      - Identity_239
      - Identity_240
      - Identity_241
      - Identity_242
      - Identity_243
      - Identity_244
      - Identity_245
      - Identity_246
      - Identity_247
      - Identity_248
      - Identity_249
      - Identity_250
      - Identity_251
      - Identity_252
      - Identity_253
      - Identity_254
      - Identity_255
      - Identity_256
      - Identity_257
      - Identity_258
      - Identity_259
      - Identity_260
      - Identity_261
      - Identity_262
      - Identity_263
      - Identity_264
      - Identity_265
      - Identity_266
      - Identity_267
      - Identity_268
      - Identity_269
      - Identity_270
      - Identity_271
      - Identity_272
      - Identity_273
      - Identity_274
      - Identity_275
      - Identity_276
      - Identity_277
      - Identity_278
      - Identity_279
      - Identity_280
      - Identity_281
      - Identity_282
      - Identity_283
      - Identity_284
      - Identity_285
      - Identity_286
      - Identity_287
      - Identity_288
      - Identity_289
      - Identity_290
      - Identity_291
      - Identity_292
      - Identity_293
      - Identity_294
      - Identity_295
      - Identity_296
      - Identity_297
      - Identity_298
      - Identity_299
      - Identity_300
      - Identity_301
      - Identity_302
      - Identity_303
      - Identity_304
      - Identity_305
      - Identity_306
      - Identity_307
      - Identity_308
      - Identity_309
      - Identity_310
      - Identity_311
      - Identity_312
      - Identity_313
      - Identity_314
      - Identity_315
      - Identity_316
      - Identity_317
      - Identity_318
      - Identity_319
      - Identity_320
      - Identity_321
      - Identity_322
      - Identity_323
      - Identity_324
      - Identity_325
      - Identity_326
      - Identity_327
      - Identity_328
      - Identity_329
      - Identity_330
      - Identity_331
      - Identity_332
      - Identity_333
      - Identity_334
      - Identity_335
      - Identity_336
      - Identity_337
      - Identity_338
      - Identity_339
      - Identity_340
      - Identity_341
      - Identity_342
      - Identity_343
      - Identity_344
      - Identity_345
      - Identity_346
      - Identity_347
      - Identity_348
      - Identity_349
      - Identity_350
      - Identity_351
      - Identity_352
      - Identity_353
      - Identity_354
      - Identity_355
      - Identity_356
      - Identity_357
      - Identity_358
      - Identity_359
      - Identity_360
      - Identity_361
      - Identity_362
      - Identity_363
      - Identity_364
      - Identity_365
      - Identity_366
      - Identity_367
      - Identity_368
      - Identity_369
      - Identity_370
      - Identity_371
      - Identity_372
      - Identity_373
      - Identity_374
      - Identity_375
      - Identity_376
      - Identity_377
      - Identity_378
      - Identity_379
      - Identity_380
      - Identity_381
      - Identity_382
      - Identity_383
      - Identity_384
      - Identity_385
      - Identity_386
      - Identity_387
      - Identity_388
      - Identity_389
      - Identity_390
      - Identity_391
      - Identity_392
      - Identity_393
      - Identity_394
      - Identity_395
      - Identity_396
      - Identity_397
      - Identity_398
      - Identity_399
      - Identity_400
      - Identity_401
      - Identity_402
      - Identity_403
      - Identity_404
      - Identity_405
      - Identity_406
      - Identity_407
      - Identity_408
      - Identity_409
      - Identity_410
      - Identity_411
      - Identity_412
      - Identity_413
      - Identity_414
      - Identity_415
      - Identity_416
      - Identity_417
      - Identity_418
      - Identity_419
      - Identity_420
      - Identity_421
      - Identity_422
      - Identity_423
      - Identity_424
      - Identity_425
      - Identity_426
      - Identity_427
      - Identity_428
      - Identity_429
      - Identity_430
      - Identity_431
      - Identity_432
      - Identity_433
      - Identity_434
      - Identity_435
      - Identity_436
      - Identity_437
      - Identity_438
      - Identity_439
      - Identity_440
      - Identity_441
      - Identity_442
      - Identity_443
      - Identity_444
      - Identity_445
      - Identity_446
      - Identity_447
      - Identity_448
      - Identity_449
      - Identity_450
      - Identity_451
      - Identity_452
      - Identity_453
      - Identity_454
      - Identity_455
      - Identity_456
      - Identity_457
      - Identity_458
      - Identity_459
      - Identity_460
      - Identity_461
      - Identity_462
      - Identity_463
      - Identity_464
      - Identity_465
      - Identity_466
      - Identity_467
      - Identity_468
      - Identity_469
      - Identity_470
      - Identity_471
      - Identity_472
      - Identity_473
      - Identity_474
      - Identity_475
      - Identity_476
      - Identity_477
      - Identity_478
      - Identity_479
      - Identity_480
      - Identity_481
      - Identity_482
      - Identity_483
      - Identity_484
      - Identity_485
      - Identity_486
      - Identity_487
      - Identity_488
      - Identity_489
      - Identity_490
      - Identity_491
      - Identity_492
      - Identity_493
      - Identity_494
      - Identity_495
      - Identity_496
      - Identity_497
      - Identity_498
      - Identity_499
      - Identity_500
      - Identity_501
      - Identity_502
      - Identity_503
      - Identity_504
      - Identity_505
      - Identity_506
      - Identity_507
      - Identity_508
      - Identity_509
      - Identity_510
      - Identity_511
      - Identity_512
      - input
      - frame
      - FrameHeight
      - FrameWidth
      - Identity