name: ms-env
channels:
  - nvidia # Ensures NVIDIA packages are prioritized
  - conda-forge
dependencies:
  - python=3.9
  - cmake
  - cudatoolkit=11.8
  - cudnn
  - ffmpeg
  - pandas
  - scikit-learn
  - jupyter
  - matplotlib
  - seaborn
  - dlib
  - pip
  - pip:
      - https://github.com/AffectAnalysisGroup/PyAFAR/releases/download/v3.0.0/PyAFAR_GPU-3.0-py3-none-any.whl
      - mediapipe