name: ms-env
channels:
  - conda-forge
dependencies:
  - python=3.9

  - cmake
  - ffmpeg
  - pandas
  - scikit-learn
  - jupyter
  - matplotlib
  - seaborn
  - dlib

  - pip
  - pip:
      - nvidia-pyindex
      - nvidia-cudnn-cu11==8.6.0.163
      - nvidia-cuda-runtime-cu11==11.8.89
      - nvidia-cuda-cupti-cu11==11.8.87
      - nvidia-cuda-nvrtc-cu11==11.8.89
      - nvidia-cublas-cu11==11.10.3.66
      - nvidia-cufft-cu11==10.9.0.58
      - nvidia-curand-cu11==10.3.0.86
      - nvidia-cusolver-cu11==11.4.1.48
      - nvidia-cusparse-cu11==11.7.5.86
      - nvidia-nvtx-cu11==11.8.86
      - https://github.com/AffectAnalysisGroup/PyAFAR/releases/download/v3.0.0/PyAFAR_GPU-3.0-py3-none-any.whl
      - mediapipe